# Generated by Django 5.1.1 on 2024-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemas', '0004_sistemas_img_alter_dados_current_alter_dados_temp_and_more'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sistemas',
            field=models.ManyToManyField(blank=True, to='Sistemas.sistemas'),
        ),
    ]
