databases:
  - name: heliumove-database
    plan: free
    region: virginia
    databaseName: heliumove
    user: internal

services:
  - type: web
    plan: free
    region: virginia
    name: heliumove
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn PI24.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: heliumove-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
