# Generated by Django 5.0.7 on 2024-08-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='datatime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
