# Generated by Django 5.1.1 on 2024-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemas', '0003_alter_dados_datatime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemas',
            name='img',
            field=models.CharField(max_length=1, null='1'),
            preserve_default='1',
        ),
        migrations.AlterField(
            model_name='dados',
            name='current',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='dados',
            name='temp',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='dados',
            name='voltage',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sistemas',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
